services:
  robot:
    container_name: robot
    build: .
    network_mode: "host"
    ipc: host
    pid: host
    devices:
      - /dev:/dev
    volumes:
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev/
        target: /run/udev/
      - type: bind
        source: /boot/firmware
        target: /boot/firmware
        read_only: false
    environment:
      PICOVOICE_API_KEY: "your_key"
      OPENAI_API_KEY: "your_key"

    cap_add: 
      - SYS_ADMIN
    privileged: true
    restart: always
    

    